version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      DB_SERVER: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: hackathon
      MYSQL_DATABASE: hackathon1
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hackathon
      MYSQL_DATABASE: hackathon1
    ports:
      - "3306:3306"
